Repository lilycollinsbnb/aoperat_website, pull requests merged in 2023-06, with the labels that each got.

#104 Create Blog “2023-06-06-jakis-test”
  src/pages/blog/2023-06-06-jakis-test.md
Labels: netlify-cms/pending_publish

#92 Create doradca-klenta
  src/pages/career/analityk.md
  src/pages/career/aplikant-na-rzeczoznawcę.md
  src/pages/career/doradca-klenta.md
  src/pages/career/koordynator-dotacji-unijnych.md
  src/pages/career/rzeczoznawca.md
  src/pages/career/sprzedawca.md
Labels: enhancement

#111 Create Blog “2023-06-27-jakie-są-sposoby-przyspieszania-wyceny”
  src/pages/blog/2023-06-27-jakie-są-sposoby-przyspieszania-wyceny.md
Labels: netlify-cms/draft
